In [1]:
import numpy as np
from numpy import array as arr

# pap._rundung() - Entwicklung

In [2]:
def _rundung_einzel(wert, präzision):
    '''
    Die Rundung mit einem Array von Nachkommastellen  (präzisionen)  funktioniert deshalb, da in rekursiven
    for-Loops die Arrays in einzelne Elemente aufgebrochen werden, welche dann gerundet werden.
    
    
    Argumente (sollten schon durch  _rundung()  passend gemacht worden sein.)
    ---------
    werte : np.ndarray (number_like), number_like
    
    präzisionen : np.ndarray (int), int
    
    
    Output
    ------
    wert_gerundet : np.ndarray (number_like), number_like
        Mit Pythons  round()  auf nächste gerade Ziffer gerundet (symmetrisches Runden).
        Form und Elemente sonst gleich wie  werte.
    '''
    
    
    
    anzahl_dimensionen = np.ndim(wert)   # Entsprechend viele Rekursionen werden stattfinden.
    
    # Eigentliche Rundung
    if anzahl_dimensionen == 0:
        wert_gerundet = round(wert, präzision)
    
    # Aufrufen von  _rundung_einzel()  um in einem for-Loop die Elemente von werte abzuarbeiten.
    elif anzahl_dimensionen > 0:
        wert_form = np.shape(wert)
        wert_gerundet = np.zeros(wert_form)
        for i in range(wert_form[0]):
            wert_gerundet[i] = _rundung_einzel(wert[i], präzision[i])
            
    return wert_gerundet   # Die gesammelten gerundeten Werte werden als Ergebnis zur vorigen Funktion
                           # zurückgeschickt.

In [3]:
def _rundung(werte, präzisionen):
    '''
    Rundet  werte  auf ihre jeweilige Anzahl Nachkommastellen  (präzisionen).
    Im Gegensatz zu  np.round()  kann diese Funktion  werte  mit ganzen Arrays von Nachkommastellen runden.
    Für Details zum Rundungsprozess siehe  _rundung_einzel().
    
    
    Argumente
    ---------
    werte : np.ndarray (number_like), number_like
        Kann beliebige Form haben und auch Einzelwert sein.
    
    präzisionen : np.ndarray (int), int
        Muss gleiche Form wie  werte  haben oder int sein.
    
    
    Output
    ------
    "wert_gerundet" : np.ndarray (number_like), number_like
        Mit Pythons  round()  auf nächste gerade Ziffer gerundet (symmetrisches Runden).
        Form und Elemente sonst gleich wie  werte.
    '''
    
    
    
    # Überprüfung und Anpassung der Argumente
    präzisionen = arr(präzisionen)  # Falls Einzelwert
    if präzisionen.dtype != int:
        print('präzisionen darf nur Integers enthalten!')
        print('Die Anzahl Stellen, auf die gerundet wird, kann nur ganzzahlig sein.')
    
    if np.shape(werte) != np.shape(präzisionen):
        if np.ndim(präzisionen) == 0:   # Falls  präzisionen  Einzelwert, dann wird
                                        # daraus ein Array derselben Form wie  werte  gemacht.
            präzisionen = np.full(np.shape(werte), präzisionen)
        else:
            print('werte und präzisionen müssen die gleiche np.shape haben!')
            print('np.shape(werte) =', np.shape(werte))
            print('np.shape(präzisionen) =', np.shape(präzisionen))
    
    
    # Eigentlicher Rundungsprozess
    return _rundung_einzel(werte, präzisionen)

In [4]:
def _negativ_wird_null(array):
    '''
    "Rampenfunktion": Die Werte von array, die negativ sind, werden durch 0 ersetzt.
    
    
    Argument
    --------
    array : np.ndarray (number_like)
    '''
    
    
    nullen = np.full(np.shape(array), 0)
    return np.where(array > 0, array, nullen)

## Tests

In [5]:
# Einzelne Zahlen
_rundung(-34.342, 2)

-34.34

In [6]:
# nicht-ganzzahlige Präzision
_rundung(34.342, 3.2)   # Soll Fehlermeldung generieren

präzisionen darf nur Integers enthalten!
Die Anzahl Stellen, auf die gerundet wird, kann nur ganzzahlig sein.


TypeError: only integer scalar arrays can be converted to a scalar index

In [7]:
# Rundung eines Arrays mit einer einzigen Präzision
_rundung(arr([100/3, -200 / 5, 300 / 7]), 1) # soll alle auf ein Kommastelle runden

array([ 33.3, -40. ,  42.9])

In [8]:
# negative Präzission
_rundung(arr([100/3, 200 / 5, 300 / 7]), -1) # soll auf Zehner runden

array([30., 40., 40.])

In [9]:
# Rundung eines Arrays mit ebenso geformten Präzisions-Array
array = arr([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) / 3
nachkommastellen = arr([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

_rundung(array, nachkommastellen)

array([[[0.3       , 0.67      ],
        [1.        , 1.3333    ]],

       [[1.66667   , 2.        ],
        [2.3333333 , 2.66666667]]])

In [10]:
# Rundung eines Arrays mit anders geformten Präzisions-Array
array = arr([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) / 3
nachkommastellen = arr([[1, 2], [3, 4], [5, 6], [7, 8]])

_rundung(array, nachkommastellen)

werte und präzisionen müssen die gleiche np.shape haben!
np.shape(werte) = (2, 2, 2)
np.shape(präzisionen) = (4, 2)


IndexError: invalid index to scalar variable.

### Rundungsgeschwindigkeiten

In [11]:
# Am schnellsten
wert_array = np.full((int(1e8), ), 16.055)
np.around(wert_array, 2)

array([16.06, 16.06, 16.06, ..., 16.06, 16.06, 16.06])

In [12]:
# Langsamer
for i in range(int(1e6)):
    round(16.055, 2)

In [13]:
# Am langsamsten
for i in np.arange(np.int(1e6)):
    np.around(16.055, 2)

In [14]:
print(f'{3.455:.0f}')
print(f'{3.455:.1f}')
print(f'{3.455:.10f}')
print(f'{3.000:.1f}')
print(f'{3.000:.10f}')

3
3.5
3.4550000000
3.0
3.0000000000
