In [1]:
import numpy as np
from numpy import array as arr

from pap import std

# Entwicklung grundlegender Statistik-Funktionen

In [2]:
'''
Benötigt:
numpy als np
np.array() als arr()

pap.std()
'''


def mittel_fehler(*args, **kwargs):
    '''
    Experimenteller Fehler des Mittelwertes
    
    Die Funktion berechnet std(X) / sqrt(N) von einer Werteverteilung X mit N Werten.
    Dabei ist std() = pap.std() also der Experimentelle Fehler des Einzelwertes.
    Somit lassen sich genau die gleichen Argumente wie in np.std() einsetzen.
    '''
    
    
    werte = args[0]
    shape = np.shape(werte)
    if shape == (0,):   # Verhindert Fehlermeldung falls werte == []
        return np.nan
    
    if 'axis' in kwargs and kwargs['axis'] != None:   
        # Zweite Bedingung im if-Satz nötig, wenn man explizit axis = None angibt.
        achsen        = kwargs['axis']
        shape_rest    = (shape[achsen]  if type(achsen) == int  
                         else arr([shape[i] for i in achsen]))
        anzahl_zahlen = np.prod(shape_rest)
    else:
        anzahl_zahlen = np.product(shape)
    
    
    fehler_des_mittelwertes = std(*args, **kwargs) / np.sqrt(anzahl_zahlen)
    return fehler_des_mittelwertes

## Tests

In [3]:
test_array = np.array([[[1, 2, 3, 4],     [5, 6, 7, 8],     [9, 10, 11, 12]], 
                       [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print('np.shape(test_array) =', np.shape(test_array))
print('Anzahl Zahlen =', np.product(np.shape(test_array)))

np.shape(test_array) = (2, 3, 4)
Anzahl Zahlen = 24


In [4]:
axis = 0
anzahl_rest = 2

print(np.std(test_array, axis = axis))
print(std(test_array, axis = axis) / np.sqrt(anzahl_rest))
print(mittel_fehler(test_array, axis = axis))

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [5]:
axis = 1
anzahl_rest = 3

print(np.std(test_array, axis = axis))
print(std(test_array, axis = axis) / np.sqrt(anzahl_rest))
print(mittel_fehler(test_array, axis = axis))

[[3.26598632 3.26598632 3.26598632 3.26598632]
 [3.26598632 3.26598632 3.26598632 3.26598632]]
[[2.30940108 2.30940108 2.30940108 2.30940108]
 [2.30940108 2.30940108 2.30940108 2.30940108]]
[[2.30940108 2.30940108 2.30940108 2.30940108]
 [2.30940108 2.30940108 2.30940108 2.30940108]]


In [6]:
axis = (1, 2)
anzahl_rest = 12

print(np.std(test_array, axis = axis))
print(std(test_array, axis = axis) / np.sqrt(anzahl_rest))
print(mittel_fehler(test_array, axis = axis))

[3.45205253 3.45205253]
[1.040833 1.040833]
[1.040833 1.040833]


In [7]:
axis = (2, 0, 1)
anzahl_rest = 24

print(np.std(test_array, axis = axis))
print(std(test_array, axis = axis) / np.sqrt(anzahl_rest))
print(mittel_fehler(test_array, axis = axis))

6.922186552431729
1.4433756729740645
1.4433756729740645


In [8]:
axis = None
anzahl_rest = 24

print(np.std(test_array, axis = axis))
print(std(test_array, axis = axis) / np.sqrt(anzahl_rest))
print(mittel_fehler(test_array, axis = axis))

6.922186552431729
1.4433756729740645
1.4433756729740645


In [10]:
test_array = np.array([])

print(np.std(test_array))
print(std(test_array))
print(mittel_fehler(test_array))

nan
nan
nan
