In [1]:
import numpy as np
from numpy import array as arr

# pap._rundung() - Entwicklung

In [2]:
def _rundung_einzel(wert, präzision):
    anzahl_dimensionen = np.ndim(wert)
    
    if anzahl_dimensionen == 0:
        wert_gerundet = round(wert, präzision)
    
    elif anzahl_dimensionen > 0:
        wert_form = np.shape(wert)
        wert_gerundet = np.zeros(wert_form)
        for i in range(wert_form[0]):
            wert_gerundet[i] = _rundung_einzel(wert[i], präzision[i])
            
    return wert_gerundet

In [3]:
def _rundung(werte, präzisionen):
    präzisionen = arr(präzisionen)
    if präzisionen.dtype != int:
        print('präzisionen darf nur Integers enthalten!')
        print('Die Anzahl Stellen, auf die gerundet wird, kann nur ganzzahlig sein.')
        return
    
    if np.shape(werte) != np.shape(präzisionen):
        if np.ndim(präzisionen) == 0:
            präzisionen = np.full(np.shape(werte), präzisionen)
        else:
            print('werte und präzisionen müssen die gleiche np.shape haben!')
            print('np.shape(werte) =', np.shape(werte))
            print('np.shape(präzisionen) =', np.shape(präzisionen))
            return
        
    return _rundung_einzel(werte, präzisionen)

## Tests

In [4]:
# Einzelne Zahlen
_rundung(-34.342, 2)

-34.34

In [5]:
# nicht-ganzzahlige Präzision
_rundung(34.342, 3.2)   # Soll Fehlermeldung generieren

präzisionen darf nur Integers enthalten!
Die Anzahl Stellen, auf die gerundet wird, kann nur ganzzahlig sein.


In [6]:
# Rundung eines Arrays mit einer einzigen Präzision
_rundung(arr([100/3, -200 / 5, 300 / 7]), 1) # soll alle auf ein Kommastelle runden

array([ 33.3, -40. ,  42.9])

In [7]:
# negative Präzission
_rundung(arr([100/3, 200 / 5, 300 / 7]), -1) # soll auf Zehner runden

array([30., 40., 40.])

In [8]:
# Rundung eines Arrays mit ebenso geformten Präzisions-Array
array = arr([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) / 3
nachkommastellen = arr([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

_rundung(array, nachkommastellen)

array([[[0.3       , 0.67      ],
        [1.        , 1.3333    ]],

       [[1.66667   , 2.        ],
        [2.3333333 , 2.66666667]]])

In [9]:
# Rundung eines Arrays mit anders geformten Präzisions-Array
array = arr([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) / 3
nachkommastellen = arr([[1, 2], [3, 4], [5, 6], [7, 8]])

_rundung(array, nachkommastellen)

werte und präzisionen müssen die gleiche np.shape haben!
np.shape(werte) = (2, 2, 2)
np.shape(präzisionen) = (4, 2)


### Rundungsgeschwindigkeiten

In [10]:
# Am schnellsten
wert_array = np.full((int(1e8), ), 16.055)
np.around(wert_array, 2)

array([16.06, 16.06, 16.06, ..., 16.06, 16.06, 16.06])

In [11]:
# Langsamer
for i in range(int(1e6)):
    round(16.055, 2)

In [12]:
# Am langsamsten
for i in np.arange(np.int(1e6)):
    np.around(16.055, 2)

In [13]:
print(f'{3.455:.0f}')
print(f'{3.455:.1f}')
print(f'{3.455:.10f}')
print(f'{3.000:.1f}')
print(f'{3.000:.10f}')

3
3.5
3.4550000000
3.0
3.0000000000
